<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('operations', ['as'=> 'operations.index', 'uses' => 'OperationController@index']);
Route::post('operations', ['as'=> 'operations.store', 'uses' => 'OperationController@store']);
Route::get('operations/create', ['as'=> 'operations.create', 'uses' => 'OperationController@create']);
Route::put('operations/{operations}', ['as'=> 'operations.update', 'uses' => 'OperationController@update']);
Route::patch('operations/{operations}', ['as'=> 'operations.update', 'uses' => 'OperationController@update']);
Route::get('operations/{id}/delete', array('as' => 'operations.delete', 'uses' => 'OperationController@getDelete'));
Route::get('operations/{id}/confirm-delete', array('as' => 'operations.confirm-delete', 'uses' => 'OperationController@getModalDelete'));
Route::get('operations/{operations}', ['as'=> 'operations.show', 'uses' => 'OperationController@show']);
Route::get('operations/{operations}/edit', ['as'=> 'operations.edit', 'uses' => 'OperationController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('types', ['as'=> 'types.index', 'uses' => 'TypeController@index']);
Route::post('types', ['as'=> 'types.store', 'uses' => 'TypeController@store']);
Route::get('types/create', ['as'=> 'types.create', 'uses' => 'TypeController@create']);
Route::put('types/{types}', ['as'=> 'types.update', 'uses' => 'TypeController@update']);
Route::patch('types/{types}', ['as'=> 'types.update', 'uses' => 'TypeController@update']);
Route::get('types/{id}/delete', array('as' => 'types.delete', 'uses' => 'TypeController@getDelete'));
Route::get('types/{id}/confirm-delete', array('as' => 'types.confirm-delete', 'uses' => 'TypeController@getModalDelete'));
Route::get('types/{types}', ['as'=> 'types.show', 'uses' => 'TypeController@show']);
Route::get('types/{types}/edit', ['as'=> 'types.edit', 'uses' => 'TypeController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('categories', ['as'=> 'categories.index', 'uses' => 'CategoryController@index']);
Route::post('categories', ['as'=> 'categories.store', 'uses' => 'CategoryController@store']);
Route::get('categories/create', ['as'=> 'categories.create', 'uses' => 'CategoryController@create']);
Route::put('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoryController@update']);
Route::patch('categories/{categories}', ['as'=> 'categories.update', 'uses' => 'CategoryController@update']);
Route::get('categories/{id}/delete', array('as' => 'categories.delete', 'uses' => 'CategoryController@getDelete'));
Route::get('categories/{id}/confirm-delete', array('as' => 'categories.confirm-delete', 'uses' => 'CategoryController@getModalDelete'));
Route::get('categories/{categories}', ['as'=> 'categories.show', 'uses' => 'CategoryController@show']);
Route::get('categories/{categories}/edit', ['as'=> 'categories.edit', 'uses' => 'CategoryController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('operationTypes', ['as'=> 'operationTypes.index', 'uses' => 'OperationTypeController@index']);
Route::post('operationTypes', ['as'=> 'operationTypes.store', 'uses' => 'OperationTypeController@store']);
Route::get('operationTypes/create', ['as'=> 'operationTypes.create', 'uses' => 'OperationTypeController@create']);
Route::put('operationTypes/{operationTypes}', ['as'=> 'operationTypes.update', 'uses' => 'OperationTypeController@update']);
Route::patch('operationTypes/{operationTypes}', ['as'=> 'operationTypes.update', 'uses' => 'OperationTypeController@update']);
Route::get('operationTypes/{id}/delete', array('as' => 'operationTypes.delete', 'uses' => 'OperationTypeController@getDelete'));
Route::get('operationTypes/{id}/confirm-delete', array('as' => 'operationTypes.confirm-delete', 'uses' => 'OperationTypeController@getModalDelete'));
Route::get('operationTypes/{operationTypes}', ['as'=> 'operationTypes.show', 'uses' => 'OperationTypeController@show']);
Route::get('operationTypes/{operationTypes}/edit', ['as'=> 'operationTypes.edit', 'uses' => 'OperationTypeController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('soldes', ['as'=> 'soldes.index', 'uses' => 'SoldeController@index']);
Route::post('soldes', ['as'=> 'soldes.store', 'uses' => 'SoldeController@store']);
Route::get('soldes/create', ['as'=> 'soldes.create', 'uses' => 'SoldeController@create']);
Route::put('soldes/{soldes}', ['as'=> 'soldes.update', 'uses' => 'SoldeController@update']);
Route::patch('soldes/{soldes}', ['as'=> 'soldes.update', 'uses' => 'SoldeController@update']);
Route::get('soldes/{id}/delete', array('as' => 'soldes.delete', 'uses' => 'SoldeController@getDelete'));
Route::get('soldes/{id}/confirm-delete', array('as' => 'soldes.confirm-delete', 'uses' => 'SoldeController@getModalDelete'));
Route::get('soldes/{soldes}', ['as'=> 'soldes.show', 'uses' => 'SoldeController@show']);
Route::get('soldes/{soldes}/edit', ['as'=> 'soldes.edit', 'uses' => 'SoldeController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('operationRecurents', ['as'=> 'operationRecurents.index', 'uses' => 'OperationRecurentController@index']);
Route::post('operationRecurents', ['as'=> 'operationRecurents.store', 'uses' => 'OperationRecurentController@store']);
Route::get('operationRecurents/create', ['as'=> 'operationRecurents.create', 'uses' => 'OperationRecurentController@create']);
Route::put('operationRecurents/{operationRecurents}', ['as'=> 'operationRecurents.update', 'uses' => 'OperationRecurentController@update']);
Route::patch('operationRecurents/{operationRecurents}', ['as'=> 'operationRecurents.update', 'uses' => 'OperationRecurentController@update']);
Route::get('operationRecurents/{id}/delete', array('as' => 'operationRecurents.delete', 'uses' => 'OperationRecurentController@getDelete'));
Route::get('operationRecurents/{id}/confirm-delete', array('as' => 'operationRecurents.confirm-delete', 'uses' => 'OperationRecurentController@getModalDelete'));
Route::get('operationRecurents/{operationRecurents}', ['as'=> 'operationRecurents.show', 'uses' => 'OperationRecurentController@show']);
Route::get('operationRecurents/{operationRecurents}/edit', ['as'=> 'operationRecurents.edit', 'uses' => 'OperationRecurentController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('operationIncommings', ['as'=> 'operationIncommings.index', 'uses' => 'OperationIncommingController@index']);
Route::post('operationIncommings', ['as'=> 'operationIncommings.store', 'uses' => 'OperationIncommingController@store']);
Route::get('operationIncommings/create', ['as'=> 'operationIncommings.create', 'uses' => 'OperationIncommingController@create']);
Route::put('operationIncommings/{operationIncommings}', ['as'=> 'operationIncommings.update', 'uses' => 'OperationIncommingController@update']);
Route::patch('operationIncommings/{operationIncommings}', ['as'=> 'operationIncommings.update', 'uses' => 'OperationIncommingController@update']);
Route::get('operationIncommings/{id}/delete', array('as' => 'operationIncommings.delete', 'uses' => 'OperationIncommingController@getDelete'));
Route::get('operationIncommings/{id}/confirm-delete', array('as' => 'operationIncommings.confirm-delete', 'uses' => 'OperationIncommingController@getModalDelete'));
Route::get('operationIncommings/{operationIncommings}', ['as'=> 'operationIncommings.show', 'uses' => 'OperationIncommingController@show']);
Route::get('operationIncommings/{operationIncommings}/edit', ['as'=> 'operationIncommings.edit', 'uses' => 'OperationIncommingController@edit']);

});


Route::group(array('prefix' => 'admin/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.'), function () {

Route::get('operationIncs', ['as'=> 'operationIncs.index', 'uses' => 'OperationIncController@index']);
Route::post('operationIncs', ['as'=> 'operationIncs.store', 'uses' => 'OperationIncController@store']);
Route::get('operationIncs/create', ['as'=> 'operationIncs.create', 'uses' => 'OperationIncController@create']);
Route::put('operationIncs/{operationIncs}', ['as'=> 'operationIncs.update', 'uses' => 'OperationIncController@update']);
Route::patch('operationIncs/{operationIncs}', ['as'=> 'operationIncs.update', 'uses' => 'OperationIncController@update']);
Route::get('operationIncs/{id}/delete', array('as' => 'operationIncs.delete', 'uses' => 'OperationIncController@getDelete'));
Route::get('operationIncs/{id}/confirm-delete', array('as' => 'operationIncs.confirm-delete', 'uses' => 'OperationIncController@getModalDelete'));
Route::get('operationIncs/{operationIncs}', ['as'=> 'operationIncs.show', 'uses' => 'OperationIncController@show']);
Route::get('operationIncs/{operationIncs}/edit', ['as'=> 'operationIncs.edit', 'uses' => 'OperationIncController@edit']);

});
